config/routes.rb
# Rails.application.routes.draw do
#   get '/sign_out_user', to: 'users#sign_out_user', as: 'sign_out_user'
#   devise_for :users
#   root 'users#index'
  
#     resources :posts, only: %i[destroy] 
  

#   resources :users, only: %i[index show] do
#     resources :posts, only: %i[index show new create] do
#       resources :comments, only: %i[new create destroy]
#       resources :likes, only: %i[new create]
#     end
#   end
# end
# Rails.application.routes.draw do
#   # Web application routes
#   resources :users do
#     resources :posts
#   end

#   # API routes
#   namespace :api, defaults: { format: 'json' } do
#     resources :users, only: [:index]
    
#     resources :posts, only: [] do
#       resources :comments, only: [:index, :create]
#     end
#   end
# end

Rails.application.routes.draw do
  # Your existing routes for the web application
  get '/sign_out_user', to: 'users#sign_out_user', as: 'sign_out_user'
  devise_for :users
  root 'users#index'
  resources :posts, only: %i[destroy] 
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create] do
      resources :comments, only: %i[new create destroy]
      resources :likes, only: %i[new create]
    end
  end

  # API routes
  namespace :api, defaults: { format: 'json' } do
    resources :users, only: [:index] do
      resources :posts, only: [:index]
    end
    
    resources :posts, only: [] do
      resources :comments, only: [:index, :create]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id

  attribute :name, :string
  attribute :photo, :string
  attribute :bio, :text
  attribute :postsCounter, :integer, default: 0

  validates :name, presence: true
  validates :postsCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def admin?
    role == 'admin'
  end

  def most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/users_controller.rb
module Api
  class UsersController < ApplicationController
    before_action :authenticate_api, except: [:index]
    def index
      @users = User.all
      render json: @users
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.includes(:posts).find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="user-container">
    <%if @users.empty?%>
        <h1>There are no users yet</h1>
    <%end%>
    <ul>
        <%@users.each do |user|%>
            <li>
                <a href="/users/<%= user.id%>">
                    <%= render partial: 'shared/user_card', locals: { user: user } %>
                </a>
            </li>
        <%end%>
    </ul>
</div>

app/views/users/show.html.erb
<%= render 'shared/user_card', user: @user %>

<div class="post">
  <h3>Bio</h3>
  <div class="post-body">
    <p><%= @user.bio %></p>
  </div>
</div>

<%@user.most_recent_posts.each do |post|%>
  <h5> <%= link_to post.title, user_post_url(@user, post) %> </h5>
  <%= render 'shared/post_card', post: post %>
<%end%>

<div class="btn-container">
  <%= link_to "See All Posts", user_posts_path(user_id: @user.id), class: 'btn center-btn'%>
</div>