config/routes.rb
# Rails.application.routes.draw do
#   get '/sign_out_user', to: 'users#sign_out_user', as: 'sign_out_user'
#   devise_for :users
#   root 'users#index'
  
#     resources :posts, only: %i[destroy] 
  

#   resources :users, only: %i[index show] do
#     resources :posts, only: %i[index show new create] do
#       resources :comments, only: %i[new create destroy]
#       resources :likes, only: %i[new create]
#     end
#   end
# end
# Rails.application.routes.draw do
#   # Web application routes
#   resources :users do
#     resources :posts
#   end

#   # API routes
#   namespace :api, defaults: { format: 'json' } do
#     resources :users, only: [:index]
    
#     resources :posts, only: [] do
#       resources :comments, only: [:index, :create]
#     end
#   end
# end

Rails.application.routes.draw do
  # Your existing routes for the web application
  get '/sign_out_user', to: 'users#sign_out_user', as: 'sign_out_user'
  devise_for :users
  root 'users#index'
  resources :posts, only: %i[destroy] 
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create] do
      resources :comments, only: %i[new create destroy]
      resources :likes, only: %i[new create]
    end
  end

  # API routes
  namespace :api, defaults: { format: 'json' } do
    resources :users, only: [:index] do
      resources :posts, only: [:index]
    end
    
    resources :posts, only: [] do
      resources :comments, only: [:index, :create]
    end
  end
end

app/views/shared/_comment_card.html.erb
<%= comment.user.name %>: <%= comment.text %>
<% if can? :destroy, comment %>
                <%= form_with model: comment, url: user_post_comment_path(comment.user, comment.post, comment), method: :delete, data: { confirm: 'Are you sure?' } do |f| %>
                  <span><%= f.submit "Delete", class: "delete-button" %></span>
                <% end %>
              <% end %>

app/views/shared/_post_card.html.erb
<div class="post">
  <div class="post-title">        
      <h3><%= post.title %></h3>
  </div>
  <div class="post-info">
      <p><%= post.text %></p>
      <div class="pull-right">
        <span>Comments: <%= post.commentsCounter %></span>,
        <span>Likes: <%= post.likesCounter %></span>
      </div>
  </div>
</div>

app/views/shared/_user_card.html.erb
<div class="user-card">
  <div class="user-image">
      <img src="<%= user.photo %>" alt=" Image of <%= user.name %>">
  </div>
  <div class="user-info">
      <h1><%= user.name %></h1>
      <span class="flex-right">Number of posts: <%= user.postsCounter %></span>
  </div>
</div>