config/routes.rb
# Rails.application.routes.draw do
#   get '/sign_out_user', to: 'users#sign_out_user', as: 'sign_out_user'
#   devise_for :users
#   root 'users#index'
  
#     resources :posts, only: %i[destroy] 
  

#   resources :users, only: %i[index show] do
#     resources :posts, only: %i[index show new create] do
#       resources :comments, only: %i[new create destroy]
#       resources :likes, only: %i[new create]
#     end
#   end
# end
# Rails.application.routes.draw do
#   # Web application routes
#   resources :users do
#     resources :posts
#   end

#   # API routes
#   namespace :api, defaults: { format: 'json' } do
#     resources :users, only: [:index]
    
#     resources :posts, only: [] do
#       resources :comments, only: [:index, :create]
#     end
#   end
# end

Rails.application.routes.draw do
  # Your existing routes for the web application
  get '/sign_out_user', to: 'users#sign_out_user', as: 'sign_out_user'
  devise_for :users
  root 'users#index'
  resources :posts, only: %i[destroy] 
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create] do
      resources :comments, only: %i[new create destroy]
      resources :likes, only: %i[new create]
    end
  end

  # API routes
  namespace :api, defaults: { format: 'json' } do
    resources :users, only: [:index] do
      resources :posts, only: [:index]
    end
    
    resources :posts, only: [] do
      resources :comments, only: [:index, :create]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments
  has_many :likes

  attribute :title, :string
  attribute :text, :text
  attribute :commentsCounter, :integer, default: 0
  attribute :likesCounter, :integer, default: 0

  after_save :update_post_counter
  after_destroy :update_post_counters

  validates :title, presence: true, length: { maximum: 250 }
  validates :text, presence: true
  validates :commentsCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likesCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_post_counter
    author.increment!(:postsCounter)
  end

  def update_post_counters
    author.decrement!(:postsCounter)
  end
end

app/controllers/api/posts_controller.rb
module Api
  class PostsController < ApplicationController
    before_action :set_user
    before_action :authenticate_api, except: [:index]

    def index
      @posts = @user.posts
      render json: @posts
    end

    private

    def set_user
      @user = User.find(params[:user_id])
    end
  end
end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class PostsController < ApplicationController
      load_and_authorize_resource

      def index
        @user = User.includes(posts: :comments).find(params[:user_id])
        @posts = @user.posts.includes(:comments)

        respond_to do |format|
          format.html
          format.json { render json: @posts }
        end
      end

      def show
        @user = User.find(params[:user_id])
        @post = @user.posts.includes(:comments).find(params[:id])

        respond_to do |format|
          format.html
          format.json { render json: @post }
        end
      end

      def new
        @user = current_user
        @post = @user.posts.build

        respond_to do |format|
          format.html
          format.json { render json: @post }
        end
      end

      def create
        @user = current_user
        @post = Post.new(
          author: @user,
          title: params[:post][:title],
          text: params[:post][:text],
          commentsCounter: 0,
          likesCounter: 0
        )

        respond_to do |format|
          if @post.save
            format.html do
              flash.now[:error] = 'Post was successfully created.'
              redirect_to user_posts_path(@user)
            end
            format.json { render json: @post, status: :created }
          else
            format.html do
              flash.now[:error] = 'Oops, something went wrong'
              render :new
            end
            format.json { render json: { errors: @post.errors.full_messages }, status: :unprocessable_entity }
          end
        end
      end

      def destroy
        @post = Post.find(params[:id])
        @post.destroy
        flash[:notice] = 'Post was Deleted successfully'

        respond_to do |format|
          format.html { redirect_to user_posts_path(current_user) }
          format.json { head :no_content }
        end
      end

      private

      def post_params
        params.require(:post).permit(:title, :text)
      end
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<%# user card %>
<a href="#">
  <%= render partial: 'shared/user_card', locals: { user: @user } %>
</a>
<div class="btn-container">
  <p class="btn"><%= link_to "Add Post", new_user_post_path %></p>
</div>

<%# Display posts and delete button for authorized users %>
<% @posts.each do |post| %>
  <div>
    <a href="<%= user_post_path(@user, post) %>">
      <%= render partial: 'shared/post_card', locals: { post: post } %>
    </a>
    <% if can? :destroy, post %>
      <%= form_with model: post, url: post_path(post), method: :delete, data: { confirm: 'Are you sure?' } do |f| %>
      <span><%= f.submit "Delete", class: "delete-button" %></span>
    <% end %>
    <% end %>
  </div>
<% end %>

<%# post card %>
<% @posts.each do |post| %>
  <div>
    <div class="comments">
      <% if post.most_recent_comments.any? %>
        <ul>
          <% post.most_recent_comments.each do |comment| %>
            <li>
              <%= render partial: 'shared/comment_card', locals: { comment: comment } %>
              
            </li>
          <% end %>
        </ul>
      <% else %>
        <p>No recent comments found.</p>
      <% end %>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<div class="post">
  <h1>Create New Post</h1>
  <%= form_with(model: [@user, @post], url: user_posts_path(@user)) do |f| %>
    <div class="f-post">
      <div class="f-label">
        <%= f.label :title %>
        <%= f.text_field :title, class: "input", required: true %>
      </div>
      <div class="f-label">
        <%= f.label :text %>
        <%= f.text_area :text, class: "input", rows: 3, cols: 25, required: true %>
      </div>
      <div class="btn-container">
        <p><%= f.submit "Add Post", class: "btn center-btn"%></p>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="post">
    <div class="post-header">
      <ul>
        <li>
          <h3>
            <%= @post.title %> 
            <span>by <%= @post.author.name %></span>
          </h3>          
        </li>
        <li class="pull-right">
          <span>Comments: <%= @post.commentsCounter %></span>,
          <span>Likes: <%= @post.likesCounter %></span>
        </li>
      </ul>
    </div>
    <div class="post-body">
        <p><%= @post.text %></p>
    </div>
    <%= form_with model: @like, url: user_post_likes_path(post_id: @post.id) do |f| %>
      <span><%= f.submit "Like", class: "btn" %></span>
    <% end %>
  </div>

  <div class="comments">
    <ul>
      <% @post.most_recent_comments.each do |comment| %>
        <li>
          <%= render partial: 'shared/comment_card', locals: { comment: comment } %>
        </li>
      <% end %>
    </ul>
    <%= link_to 'Add Comment', new_user_post_comment_path(@user, @post), class: 'btn' %>
  </div>
</div>